name: 's3_snowflake_elt'
version: '1.0.0'
config-version: 2

profile: 's3_snowflake'

model-paths: ["models"]  # Ensures dbt looks inside 'models/'
test-paths: ["tests"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  s3_snowflake_elt:
    +materialized: table
    staging:  # Ensure this matches your folder structure
      +schema: staging
